# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Nodejs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      minio:
        image: bitnami/minio:latest
        env:
          MINIO_ACCESS_KEY: "access-mock-key"
          MINIO_SECRET_KEY: "secret-mock-key"
          MINIO_PORT_NUMBER: 9000
        ports:
          - 9000:9000

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: yarn install
      - name: build
        run: yarn build
      - name: test
        run: yarn test:coverage
        env:
          CI: true
          ENDPOINT: "http://localhost:9000"
          ACCESS_KEY: "access-mock-key"
          SECRET_KEY: "secret-mock-key"
      - name: release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
